apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: influxdb-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: influxdb
        image: influxdb_image
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        - name: dockersock
          mountPath: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: influxdb
      port: 8086
