apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: mysql-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mysql_volume"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
  labels:
    type: local
spec:
  storageClassName: influxdb-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/influxdb-volume"
