apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
  - name: ftp20
    port: 20
  - name: ftp21
    port: 21
  - name: ftp3000
    port: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
